#!/bin/bash

# batch-render
# 
# usage:
# batch-render MXS_DIR OUTPUT_DIR NUM_NODES [PROJECT_NAME]
# 
# Requires render-thread.pbs
# 
# This script finds all the .mxs files in MXS_DIR, renders all of them with
# Maxwell Renderer using as many cluster jobs as it can without exceeding
# NUM_NODES, and outputs the resulting png images to OUTPUT_DIR with the same
# names, plus diagnostic output and error log files.

set -o nounset
set -o errexit

# parameters
if [ "$1" == "-r" ]
then
  RECURSE=1
  MXS_DIR=$2
  OUTPUT_DIR=$3
  NUM_NODES=$4
  PROJNAME=${5-render} #optional
else
  RECURSE=0
  MXS_DIR=$1
  OUTPUT_DIR=$2
  NUM_NODES=$3
  PROJNAME=${4-render} #optional
fi


# global variables
THREAD_NUM=0
DIR=$( cd "$( dirname "$0" )" && pwd )

# function initializes temp file that lists MXS file paths
InitMXSFileList () {
  MXS_FILE_LIST_PATH=$(mktemp tmp_batch_render.XXXXXXXXXX) || { echo "Failed to create temp file"; exit 1; }
  NUM_MXS_FILES_LISTED=0
}

# function adds the parameter to the MXS file path list
AddToMXSFileList () {
  echo $1 >> $MXS_FILE_LIST_PATH
  NUM_MXS_FILES_LISTED=$((NUM_MXS_FILES_LISTED+1))
}

# function starts a job to render the current list of files using Maxwell,
# clears the list and increments the thread number
StartRenderJob () {
  THREAD_NUM=$((THREAD_NUM+1))
  echo "Starting thread $THREAD_NUM with $NUM_MXS_FILES_LISTED files"
  qsub -N "${PROJNAME}_thread_${THREAD_NUM}"  -l walltime=23:00:00 \
    -l nodes=1:ppn=12,mem=10gb \
    -o ${OUTPUT_DIR}/${PROJNAME}_thread_${THREAD_NUM}_output.txt \
    -e ${OUTPUT_DIR}/${PROJNAME}_thread_${THREAD_NUM}_error.txt \
    -v MXS_FILE_LIST_PATH=${MXS_FILE_LIST_PATH},OUTPUT_DIR=${OUTPUT_DIR},MXS_DIR=${MXS_DIR} \
    ${DIR}/render-thread.pbs
}

# init log
echo "Running batch-render"
echo "Started $(date +%F\ %T)"

# calculated constants
if [ $RECURSE -eq 1 ]
then
  NUM_MXS_FILES=$(find ${MXS_DIR} -name *.mxs -type f | wc -l)
else
  NUM_MXS_FILES=$(find ${MXS_DIR} -name *.mxs -maxdepth 0 -type f | wc -l)
fi
NUM_MXS_FILES_PER_NODE=$(((NUM_MXS_FILES + (NUM_NODES-1))/NUM_NODES))

# log info
echo "MXS_DIR = $MXS_DIR"
echo "OUTPUT_DIR = $OUTPUT_DIR"
echo "NUM_NODES = $NUM_NODES"
echo "PROJNAME = $PROJNAME"
echo "NUM_MXS_FILES = $NUM_MXS_FILES"
echo "NUM_MXS_FILES_PER_NODE = $NUM_MXS_FILES_PER_NODE"

InitMXSFileList

# create output directory if necessary
if [ ! -d ${OUTPUT_DIR} ]
then
  mkdir ${OUTPUT_DIR}
fi

for directory in $( find MXS_DIR -type d ! -name . )
do
  new_directory=$( echo ${directory} | sed "s%\./%${OUTPUT_DIR}/%" )
  echo "mkdir -p \"${new_directory}\""
  mkdir -p "${new_directory}"
done

# iterate over each mxs file
if [ $RECURSE -eq 1 ]
then
  MXS_PATHS=$(find ${MXS_DIR} -name *.mxs -type f)
else
  MXS_PATHS=$(find ${MXS_DIR} -name *.mxs -maxdepth 0 -type f)
fi

for MXS_PATH in ${MXS_PATHS}
do 
  #temp=${MXS_PATH##*/}
  #MXS_NAME=${temp%.*}  

  AddToMXSFileList ${MXS_PATH}

  if [ $NUM_MXS_FILES_LISTED -eq $NUM_MXS_FILES_PER_NODE ]
  then
    StartRenderJob
    InitMXSFileList
  fi
done

# final job for leftover files
if [ $NUM_MXS_FILES_LISTED -gt 0 ]
then
  StartRenderJob
else
  rm ${MXS_FILE_LIST_PATH}
fi

echo "Ended $(date +%F\ %T)"
