#!/bin/bash


# Usage: framegen-render MAIN_DIR FILES_PER_THREAD MAX_NUM_THREADS [PROJNAME]
# 
# Parameters:
#   MAIN_DIR : Directory containing JSON and MXS files in expected structure
#   FILES_PER_THREAD : Maximum number of files for each render thread
#   MAX_NUM_THREADS : Maximum number of threads to run at once
#   PROJNAME : (optional) Project name
# 
# Requires framegen-pipe.pbs
# 
# Concurrently runs framegen to generate the MXS files for each frame, and
# batch-render-stream to render each MXS file as they are created.

set -o nounset
set -o errexit

DIR=$( cd "$( dirname "$0" )" && pwd )

MAIN_DIR=$1
FILES_PER_THREAD=$2
MAX_NUM_THREADS=$3
PROJNAME=${4-render}

echo "MAIN_DIR = ${MAIN_DIR}"
echo "FILES_PER_THREAD = $FILES_PER_THREAD"
echo "MAX_NUM_THREADS = $MAX_NUM_THREADS"
echo "PROJNAME = ${PROJNAME}"

qsub -N "${PROJNAME}_framegen_pipe" -l walltime=23:00:00 \
  -l nodes=1:ppn=1,mem=2gb \
  -o ${PROJNAME}_framegen_pipe.o \
  -e ${PROJNAME}_framegen_pipe.e \
  -v MAIN_DIR=${MAIN_DIR},FILES_PER_THREAD=${FILES_PER_THREAD},MAX_NUM_THREADS=${MAX_NUM_THREADS},PROJNAME=${PROJNAME} \
  ${DIR}/framegen-pipe.pbs
